common:
  _name: default
  seed: 39
  device: cuda

model:
  _name: emotion-wav2vec2
  hidden_dim: 384
  frontend_model:
    _name: wav2vec2-base
    path: /home/poyu39/github/poyu39/emotion-conformer/model/wav2vec2-base/librispeech_iemocap/checkpoints/checkpoint_best.pt
    freeze: True

dataset:
  _name: IEMOCAP
  d_path: /home/poyu39/github/poyu39/emotion-conformer/dataset/IEMOCAP_full_release
  ratio: [0.8, 0.1, 0.1]
  batch_size: 32
  num_workers: 28

train:
  fold: 1
  epoch: 200

optimizer:
  _name: adam
  lr: 5e-4
  weight_decay: 1e-4

scheduler:
  _name: cosine
  T_max: 200
  eta_min: 1e-5
  last_epoch: -1